### ISSUE TITLE
Compiled Version

### ISSUE THREAD

**Issue by ghost** [mairatma/html2incdom#1]
Hi,

Could you please upload or commit the compiled version of html2incdom.
I am not familiar with gulp.

Thanks

**Comment by mairatma** [comment]
If you install via [npm](https://www.npmjs.com/package/html2incdom) you'll already be able to access the compiled version.

It's not nice pushing build files to repos, so the usual practice is only publishing to either npm or bower.

If you're not used to npm, here are the steps you'll need to use this:
1. Install [NodeJS](https://nodejs.org/en/)
2. On your terminal type `npm install html2incdom`
3. Access the file at `node_modules/html2incdom/dist`

Let me know if that didn't work for some reason :)
