### ISSUE TITLE
HTML2IncDom.run is undefined

### ISSUE THREAD

**Issue by ghost** [mairatma/html2incdom#2]
Hi again,

I am able to compile html2incdom but cant use it with Chrome. Although html2incdom-withParser.js contains `HTML2IncDom.run` method Chrome gives undefined error.

Thanks

**Comment by mairatma** [comment]
Oh right, you have to access `HTML2IncDom.default.run`, since it's compiled from es6. I've just tried it out and it works :)

**Comment by ghost** [comment]
Thanks so much, it works now.
